### ISSUE TITLE
src/merge_two_sorted_lists.rs fails when list contains i32::MAX

### ISSUE THREAD

**Issue by rainliu** [Aloxaf/LeetCode-Rust#2]
For example:
[1,2,2147483647]
[1,2,4]

But the following example passed
[1,2,4]
[1,2,2147483647]

The reason is due to the following two lines:
 let (x, y) = (x.unwrap_or(std::i32::MAX), y.unwrap_or(std::i32::MAX));

 let n = if x < y {

**Comment by Aloxaf** [comment]
Thank you for pointing out my mistake!
It seems that using special values is not a good idea.

**Comment by Aloxaf** [comment]
I have switched to a more intuitive algorithm,
This bug should have been fixed now.
